config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  resources :keywords
  resources :todos
  resources :actions
  resources :users
  resources :reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/keyword.rb
class Keyword < ApplicationRecord
	belongs_to :report
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Mots-clés ajouté avec succès.' }
        format.json { render :show, status: :created, location: @keyword }
        format.js
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Mots-clés modfié avec succès.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Mots-clés supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:label, :report_id)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
  <%= form_with(model: keyword, local: true) do |form| %>
    <% if keyword.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>
        <ul>
        <% keyword.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label for="exampleFormControlTextarea1">Mots-clés</label>
      <%= form.text_field :label %>
    </div>

    <div class="field">
      <label for="exampleFormControlTextarea1">Attaché à la situation:</label>
      <%= form.text_field :report_id %>
    </div>

    <div class="actions">
      <%= form.submit "Enregistrer", class: 'btn btn-primary'   %>
    </div>
  <% end %>
</div>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Voir', @keyword, type:"button", class:"btn btn-outline-info " %> |
<%= link_to 'Retour', keywords_path, type:"button", class:"btn btn-outline-dark "  %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gérer les mots clés</h1>
<%= link_to 'Ajouter un mot-clé', new_keyword_path, type:"button", class:"btn btn-outline-success"  %>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Libellé</th>
      <th>Rattaché au signalement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.label %></td>
        <td><%= keyword.report.label %></td>
        <td><%= link_to 'voir', keyword %></td>
        <td><%= link_to 'Editer', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Supprimer', keyword, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <p>
        <strong>Mots-clés :</strong>
        <%= @keyword.label %>
      </p>
      <p>
        <strong>Attaché à la situation:</strong>
        <% @signalement = Report.find_by(id: @keyword.report_id)%>
        <%= @signalement.label %>
      </p>
      <hr>
      <div>
        <%= link_to 'Editer', edit_keyword_path(@keyword) , type:"button", class:"btn btn-outline-dark"  %> |
        <%= link_to 'Retour', keywords_path, type:"button", class:"btn btn-outline-dark" %> |
        <%= link_to 'Accueil', root_path, type:"button", class:"btn btn-outline-dark"  %>
      </div>
    </div>
  </div>
</div>