config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  resources :keywords
  resources :todos
  resources :actions
  resources :users
  resources :reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
	has_many :keywords
	has_many :todos

	
	def self.search(search)
		if search
			libelle = Report.find_by(label: search)
			if libelle
				self.where(report_id: libelle)
			else
				Report.all
			end
		else
			Report.all
		end
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    
    @reports = Report.all
    @search = params["search"]
    if @search.present?
      @label = @search[:label]
      @reports = Report.where("label ILIKE ?", "%#{@label}%")
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Signalement a été créé.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Signalement a été mis à jour.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Signalement a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:label, :descrption, :visible, :search)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="form-group">
    <label for="exampleFormControlInput1">Libellé de la situation</label>

      <%= form.text_field :label, type:"text", class:"form-control" %>
    </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea1">Description de la situation</label>

      <%= form.text_area :descrption, type:"textarea", class:"form-control", rows:"5" %>
    </div>


    <div class="form-group form-check">
      <label for="exampleFormControlTextarea1">Validée par le comité</label>

      <%= form.check_box :visible, class:"form-check-label" %>
    </div>
    <br>
    
    <!--liste actions et add todo -->
    <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Action</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <%= link_to 'Ajouter actions', new_todo_path, type:"button", class:"btn btn-outline-danger"  %>
    <% @afaire = Todo.where(report_id: @report.id)%>
    <tbody>
      <% @afaire.each do |t| %>
      <tr>      
        <td><%= t.label%></td>
        <td><%= t.action_desc%></td>
        <% end %>
      </tr>
    </tbody>
  </table>
  
  <!--liste keywords et add keyword -->
  
  <div class="card bg-light mb-3">
    
    <div class="card-body">
    <%= link_to 'Ajouter mots-clés', new_keyword_path, type:"button", class:"btn btn-outline-success" %>
      <div id="action" class="shadow-lg h-100 p-3 mb-5 bg-white rounded">
        <% @motclef = Keyword.where(report_id: @report.id)%>
        <strong>Mots(s)-clés:</strong><br>
        <% @motclef.each do |m| %>
          <%= m.label%> <br>
        <% end %>
      </div>
    </div>
  </div>

  <div class="actions center">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary' %>
  </div>
</div>

<% end %>

app/views/reports/edit.html.erb
<div class="containter p-3 center">
	<h1 class="text-center">Modifier une situation</h1>

	<%= render 'form', report: @report %>
	
	<div class="text-center">
		<%= link_to 'Voir', edit_report_path(@report), type:"button", class:"btn btn-outline-info " %> |
		<%= link_to 'Retour', reports_path, type:"button", class:"btn btn-outline-dark "  %>
	</div>
</div>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Zone formualaire de recherche 
<div class="container">
  <%= simple_form_for :search, url: reports_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :label, label: false, placeholder: 'mots-clés', input_html: {value: ""} %>   
    <%= f.submit "Chercher", class: "btn btn-primary" %>
  <% end %>
</div>
-->

<div class="container">
  <h1>Les situations</h1><br> 
  <%= link_to 'Créer une situation', new_report_path, type:"button", class:"btn btn-outline-success" %>
  <hr>  
  <div class="row">
    <% @reports.order(id: :desc).each do |report| %>
      <div class="col-4">
        <h5><%= report.label %>
        <p><%= report.descrption %><br>
        <% if report.visible %>
          <p class="card-text text-success">Décision comité : validé</p>
        <% else %>
          <p class="card-text text-warning">Décision comité : en-cours de validation</p>
        <% end %>
        <%= link_to 'voir', report, type:"button", class:"btn btn-outline-success" %>        
        <%= link_to 'éditer', edit_report_path(report), type:"button", class:"btn btn-outline-primary" %>
        <%= link_to 'supprimer', report, method: :delete, type:"button", class:"btn btn-outline-danger", data: { confirm: 'Etes-vous sûr ?' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/new.html.erb
<div class="containter p-3 center">
	<h3 class="text-center">Créer une situation</h3>

	<%= render 'form', report: @report %>
	
	<%= link_to 'Retour', reports_path, type:"button", class:"btn btn-outline-dark" %>
</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
          <p>
            <div class="card-header text-white bg-primary"><h3><%= @report.label %></h3></div>
          </p>

          <p>
            <strong>Descrption:</strong>
            <%= @report.descrption %>
          </p>

          <p>
              <% if @report.visible %>
                <p class="card-text text-success">Décision comité : validé</p>
              <% else %>
                <p class="card-text text-warning">Décision comité : en-cours de validation</p>
              <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="card bg-light mb-3">
      <div class="card-body">
        <div id="action" class="shadow-lg h-100 p-3 mb-5 bg-white rounded">
          <% @motclef = Keyword.where(report_id: @report.id)%>
          <strong>Mots(s)-clés:</strong><br>
          <% @motclef.each do |m| %>
            <%= m.label%> <br>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Action</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <% @afaire = Todo.where(report_id: @report.id)%>
    <tbody>
      <% @afaire.each do |t| %>
      <tr>      
        <td><%= t.label%></td>
        <td><%= t.action_desc%></td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <hr>
  <div>
    <%= link_to 'Editer', edit_report_path(@report), type:"button", class:"btn btn-outline-dark"  %> |
    <%= link_to 'Retour', reports_path, type:"button", class:"btn btn-outline-dark" %> |
    <%= link_to 'Accueil', root_path, type:"button", class:"btn btn-outline-dark"  %>
  </div>
</div>